[project]
name = "latest-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi>=0.119.1",
    "loguru>=0.7.3",
    "ruff>=0.14.1",
    "uvicorn[standard]>=0.38.0",
]
